export const beastTribes = [
  "Amalj'aa",
  "Sylph",
  "Kobold",
  "Sahagin",
  "Ixal",
  "Vanu_Vanu",
  "Gnath",
  "Moogle",
  "Kojin",
  "Ananta",
  "Namazu",
  "Pixie",
  "Dwarf",
  "Qiqirn",
  "Matanga",
  "Omicron",
  "Goblin",
  "Mamool_Ja",
  "Dragon",
  "Lupin",
  "Bangaa",
  "Seeq",
  "Nu_Mou",
  "Loporrit",
  "Ea",
  "Karellian",
  "Grebuloff",
  "Nibirun",
  "Gordhonite",
];

/**
 * Extracted from https://ffxiv.consolegameswiki.com/wiki, because game data doesn't have reliable tribe info.
 */
export const beastTribeNpcs = [
  {
    name: "Adroit Amaro Tamer",
    race: "Amalj'aa",
    link: "/wiki/Adroit_Amaro_Tamer",
    gender: "Male",
  },
  {
    name: "Aged Amaro Tamer",
    race: "Amalj'aa",
    link: "/wiki/Aged_Amaro_Tamer",
    gender: "Male",
  },
  {
    name: "Amalj'aa Drakelasher",
    race: "Amalj'aa",
    link: "/wiki/Amalj%27aa_Drakelasher",
  },
  {
    name: "Amalj'aa Hatchling",
    race: "Amalj'aa",
    link: "/wiki/Amalj%27aa_Hatchling",
  },
  {
    name: "Amalj'aa Mender",
    race: "Amalj'aa",
    link: "/wiki/Amalj%27aa_Mender",
  },
  {
    name: "Amalj'aa Runagate",
    race: "Amalj'aa",
    link: "/wiki/Amalj%27aa_Runagate",
  },
  {
    name: "Amalj'aa Vendor",
    race: "Amalj'aa",
    link: "/wiki/Amalj%27aa_Vendor",
  },
  {
    name: "Amalj'aa War Chief",
    race: "Amalj'aa",
    link: "/wiki/Amalj%27aa_War_Chief",
  },
  {
    name: "Amalj'aa Warrior",
    race: "Amalj'aa",
    link: "/wiki/Amalj%27aa_Warrior",
  },
  {
    name: "Amaro Handler",
    race: "Amalj'aa",
    link: "/wiki/Amaro_Handler",
  },
  {
    name: "Amaro Tamer",
    race: "Amalj'aa",
    link: "/wiki/Amaro_Tamer",
  },
  {
    name: "Aspiring Amaro Tamer",
    race: "Amalj'aa",
    link: "/wiki/Aspiring_Amaro_Tamer",
  },
  {
    name: "Bugaal Ja",
    race: "Amalj'aa",
    link: "/wiki/Bugaal_Ja",
    gender: "Male",
  },
  {
    name: "Enraged Amalj'aa",
    race: "Amalj'aa",
    link: "/wiki/Enraged_Amalj%27aa",
  },
  {
    name: "Fibubb Gah",
    race: "Amalj'aa",
    link: "/wiki/Fibubb_Gah",
    gender: "Male",
  },
  {
    name: "Knem Cheleim-In",
    race: "Amalj'aa",
    link: "/wiki/Knem_Cheleim-In",
    gender: "Female",
  },
  {
    name: "Paglth'an Flamekeeper",
    race: "Amalj'aa",
    link: "/wiki/Paglth%27an_Flamekeeper",
  },
  {
    name: "Ameexia",
    race: "Sylph",
    link: "/wiki/Ameexia",
    gender: "Female",
  },
  {
    name: "Amiable Sylph",
    race: "Sylph",
    link: "/wiki/Amiable_Sylph",
  },
  {
    name: "Captured Sylph",
    race: "Sylph",
    link: "/wiki/Captured_Sylph",
  },
  {
    name: "Cheerful Sylph",
    race: "Sylph",
    link: "/wiki/Cheerful_Sylph",
  },
  {
    name: "Claxio",
    race: "Sylph",
    link: "/wiki/Claxio",
    gender: "Male",
  },
  {
    name: "Cocksure Crook",
    race: "Sylph",
    link: "/wiki/Cocksure_Crook",
  },
  {
    name: "Dellexia",
    race: "Sylph",
    link: "/wiki/Dellexia",
    gender: "Female",
  },
  {
    name: "Diluxio",
    race: "Sylph",
    link: "/wiki/Diluxio",
    gender: "Male",
  },
  {
    name: "Elated Sylph",
    race: "Sylph",
    link: "/wiki/Elated_Sylph",
  },
  {
    name: "Excited Amphibian-lover",
    race: "Sylph",
    link: "/wiki/Excited_Amphibian-lover",
  },
  {
    name: "Exhausted Sylph",
    race: "Sylph",
    link: "/wiki/Exhausted_Sylph",
  },
  {
    name: "Exultant Interloper",
    race: "Sylph",
    link: "/wiki/Exultant_Interloper",
  },
  {
    name: "Frixio",
    race: "Sylph",
    link: "/wiki/Frixio",
    gender: "Male",
  },
  {
    name: "Irritable Sylph",
    race: "Sylph",
    link: "/wiki/Irritable_Sylph",
  },
  {
    name: "Knolexia",
    race: "Sylph",
    link: "/wiki/Knolexia",
    gender: "Female",
  },
  {
    name: "Komuxio",
    race: "Sylph",
    link: "/wiki/Komuxio",
    gender: "Male",
  },
  {
    name: "Laxio",
    race: "Sylph",
    link: "/wiki/Laxio",
    gender: "Male",
  },
  {
    name: "Mellow Sylph",
    race: "Sylph",
    link: "/wiki/Mellow_Sylph",
  },
  {
    name: "Moxia",
    race: "Sylph",
    link: "/wiki/Moxia",
    gender: "Female",
  },
  {
    name: "Nathaxio",
    race: "Sylph",
    link: "/wiki/Nathaxio",
    gender: "Male",
  },
  {
    name: "Noraxia",
    race: "Sylph",
    link: "/wiki/Noraxia",
    gender: "Female",
  },
  {
    name: "Olmxio",
    race: "Sylph",
    link: "/wiki/Olmxio",
    gender: "Male",
  },
  {
    name: "Orphaned Sylph",
    race: "Sylph",
    link: "/wiki/Orphaned_Sylph",
  },
  {
    name: "Peculiar Sylph",
    race: "Sylph",
    link: "/wiki/Peculiar_Sylph",
  },
  {
    name: "Pelixia",
    race: "Sylph",
    link: "/wiki/Pelixia",
    gender: "Female",
  },
  {
    name: "Phanaxio of the New Leaf",
    race: "Sylph",
    link: "/wiki/Phanaxio_of_the_New_Leaf",
    gender: "Male",
  },
  {
    name: "Ponnixia",
    race: "Sylph",
    link: "/wiki/Ponnixia",
    gender: "Female",
  },
  {
    name: "Tonaxia",
    race: "Sylph",
    link: "/wiki/Tonaxia",
  },
  {
    name: "Unsure Accomplice",
    race: "Sylph",
    link: "/wiki/Unsure_Accomplice",
  },
  {
    name: "Wily Whiner",
    race: "Sylph",
    link: "/wiki/Wily_Whiner",
  },
  {
    name: "13th Order Alchemist",
    race: "Kobold",
    link: "/wiki/13th_Order_Alchemist",
  },
  {
    name: "13th Order Alchemist Ga Zi",
    race: "Kobold",
    link: "/wiki/13th_Order_Alchemist_Ga_Zi",
  },
  {
    name: "13th Order Fugleman Zo Ga",
    race: "Kobold",
    link: "/wiki/13th_Order_Fugleman_Zo_Ga",
  },
  {
    name: "13th Order Scholar",
    race: "Kobold",
    link: "/wiki/13th_Order_Scholar",
  },
  {
    name: "175th Order Alchemist",
    race: "Kobold",
    link: "/wiki/175th_Order_Alchemist",
  },
  {
    name: "175th Order Alchemist Bi Bi",
    race: "Kobold",
    link: "/wiki/175th_Order_Alchemist_Bi_Bi",
    gender: "Female",
  },
  {
    name: "175th Order Priest",
    race: "Kobold",
    link: "/wiki/175th_Order_Priest",
  },
  {
    name: "175th Order Quarryman",
    race: "Kobold",
    link: "/wiki/175th_Order_Quarryman",
  },
  {
    name: "269th Order Mendicant Da Za",
    race: "Kobold",
    link: "/wiki/269th_Order_Mendicant_Da_Za",
  },
  {
    name: "2nd Order Patriarch Za Da",
    race: "Kobold",
    link: "/wiki/2nd_Order_Patriarch_Za_Da",
  },
  {
    name: "789th Order Acolyte Ba Go",
    race: "Kobold",
    link: "/wiki/789th_Order_Acolyte_Ba_Go",
  },
  {
    name: "789th Order Craftsman Bo Gu",
    race: "Kobold",
    link: "/wiki/789th_Order_Craftsman_Bo_Gu",
  },
  {
    name: "789th Order Dustman Bo Bu",
    race: "Kobold",
    link: "/wiki/789th_Order_Dustman_Bo_Bu",
  },
  {
    name: "789th Order Dustman Bo Zu",
    race: "Kobold",
    link: "/wiki/789th_Order_Dustman_Bo_Zu",
  },
  {
    name: "789th Order Pickman Gi Gu",
    race: "Kobold",
    link: "/wiki/789th_Order_Pickman_Gi_Gu",
  },
  {
    name: "Battle-ready Mord",
    race: "Kobold",
    link: "/wiki/Battle-ready_Mord",
    gender: "Male",
  },
  {
    name: "Bhil Bil",
    race: "Kobold",
    link: "/wiki/Bhil_Bil",
    gender: "Male",
  },
  {
    name: "Bhol Bol",
    race: "Kobold",
    link: "/wiki/Bhol_Bol",
    gender: "Male",
  },
  {
    name: "Bhun Bun",
    race: "Kobold",
    link: "/wiki/Bhun_Bun",
  },
  {
    name: "Bombardier Researcher",
    race: "Kobold",
    link: "/wiki/Bombardier_Researcher",
    gender: "Male",
  },
  {
    name: "Building Material Supplier",
    race: "Kobold",
    link: "/wiki/Building_Material_Supplier",
    gender: "Female",
  },
  {
    name: "Cactus Trader",
    race: "Kobold",
    link: "/wiki/Cactus_Trader",
    gender: "Male",
  },
  {
    name: "Captured Kobold",
    race: "Kobold",
    link: "/wiki/Captured_Kobold",
  },
  {
    name: "Comely Kobold Lass",
    race: "Kobold",
    link: "/wiki/Comely_Kobold_Lass",
    gender: "Female",
  },
  {
    name: "Cowering Kobold",
    race: "Kobold",
    link: "/wiki/Cowering_Kobold",
  },
  {
    name: "Crazed Kobold",
    race: "Kobold",
    link: "/wiki/Crazed_Kobold",
  },
  {
    name: "Expectant Mord Merchant",
    race: "Kobold",
    link: "/wiki/Expectant_Mord_Merchant",
    gender: "Male",
  },
  {
    name: "Fetching Kobold Lass",
    race: "Kobold",
    link: "/wiki/Fetching_Kobold_Lass",
    gender: "Female",
  },
  {
    name: "Fledgling Scavenger",
    race: "Kobold",
    link: "/wiki/Fledgling_Scavenger",
    gender: "Male",
  },
  {
    name: "Foolhardy Mord",
    race: "Kobold",
    link: "/wiki/Foolhardy_Mord",
  },
  {
    name: "Forbidden Crystal Peddler",
    race: "Kobold",
    link: "/wiki/Forbidden_Crystal_Peddler",
  },
  {
    name: "Ga Bu",
    race: "Kobold",
    link: "/wiki/Ga_Bu",
    gender: "Male",
  },
  {
    name: "Ghel Gel",
    race: "Kobold",
    link: "/wiki/Ghel_Gel",
  },
  {
    name: "Ghen Gen",
    race: "Kobold",
    link: "/wiki/Ghen_Gen",
    gender: "Male",
  },
  {
    name: "Ghil Gil",
    race: "Kobold",
    link: "/wiki/Ghil_Gil",
    gender: "Male",
  },
  {
    name: "Ghin Gin",
    race: "Kobold",
    link: "/wiki/Ghin_Gin",
    gender: "Male",
  },
  {
    name: "Ghon Gon",
    race: "Kobold",
    link: "/wiki/Ghon_Gon",
    gender: "Male",
  },
  {
    name: "Ghon Gon's Nephew",
    race: "Kobold",
    link: "/wiki/Ghon_Gon%27s_Nephew",
    gender: "Male",
  },
  {
    name: "Ghul Gul",
    race: "Kobold",
    link: "/wiki/Ghul_Gul",
  },
  {
    name: "Ghun Gun",
    race: "Kobold",
    link: "/wiki/Ghun_Gun",
    gender: "Male",
  },
  {
    name: "Koboldling",
    race: "Kobold",
    link: "/wiki/Koboldling",
    gender: "Male",
  },
  {
    name: "Skittish Mord",
    race: "Kobold",
    link: "/wiki/Skittish_Mord",
    gender: "Male",
  },
  {
    name: "Amshs Aath",
    race: "Sahagin",
    link: "/wiki/Amshs_Aath",
  },
  {
    name: "Belligerent Sahagin",
    race: "Sahagin",
    link: "/wiki/Belligerent_Sahagin",
  },
  {
    name: "Bouu",
    race: "Sahagin",
    link: "/wiki/Bouu",
    gender: "Male",
  },
  {
    name: "Denn the Orcatoothed",
    race: "Sahagin",
    link: "/wiki/Denn_the_Orcatoothed",
  },
  {
    name: "Deushs Aath",
    race: "Sahagin",
    link: "/wiki/Deushs_Aath",
  },
  {
    name: "Distressed Ondo",
    race: "Sahagin",
    link: "/wiki/Distressed_Ondo",
  },
  {
    name: "Doww",
    race: "Sahagin",
    link: "/wiki/Doww",
  },
  {
    name: "Fyuu",
    race: "Sahagin",
    link: "/wiki/Fyuu",
    gender: "Male",
  },
  {
    name: "Govv",
    race: "Sahagin",
    link: "/wiki/Govv",
    gender: "Male",
  },
  {
    name: "Indigo Matriarch",
    race: "Sahagin",
    link: "/wiki/Indigo_Matriarch",
  },
  {
    name: "Noll",
    race: "Sahagin",
    link: "/wiki/Noll",
  },
  {
    name: "Sahagin Sentry (NPC)",
    race: "Sahagin",
    link: "/wiki/Sahagin_Sentry_(NPC)",
  },
  {
    name: "Shivering Sahagin",
    race: "Sahagin",
    link: "/wiki/Shivering_Sahagin",
  },
  {
    name: "Stalwart Sahagin Youth",
    race: "Sahagin",
    link: "/wiki/Stalwart_Sahagin_Youth",
  },
  {
    name: "Stoic Sahagin",
    race: "Sahagin",
    link: "/wiki/Stoic_Sahagin",
  },
  {
    name: "Bozol Eduan the Exact",
    race: "Ixal",
    link: "/wiki/Bozol_Eduan_the_Exact",
    gender: "Male",
  },
  {
    name: "Dozol Meloc",
    race: "Ixal",
    link: "/wiki/Dozol_Meloc",
    gender: "Male",
  },
  {
    name: "Dozol Meloc the Yea-sayer",
    race: "Ixal",
    link: "/wiki/Dozol_Meloc_the_Yea-sayer",
    gender: "Male",
  },
  {
    name: "Duzal Meyean the Steady",
    race: "Ixal",
    link: "/wiki/Duzal_Meyean_the_Steady",
    gender: "Male",
  },
  {
    name: "Ehcatl Nine Carrier",
    race: "Ixal",
    link: "/wiki/Ehcatl_Nine_Carrier",
  },
  {
    name: "Ehcatl Nine Dropper",
    race: "Ixal",
    link: "/wiki/Ehcatl_Nine_Dropper",
  },
  {
    name: "Ehcatl Nine Foreman",
    race: "Ixal",
    link: "/wiki/Ehcatl_Nine_Foreman",
  },
  {
    name: "Ehcatl Nine Manciple",
    race: "Ixal",
    link: "/wiki/Ehcatl_Nine_Manciple",
    gender: "Male",
  },
  {
    name: "Ehcatl Nine Silencer",
    race: "Ixal",
    link: "/wiki/Ehcatl_Nine_Silencer",
  },
  {
    name: "Fleet-footed Ixal",
    race: "Ixal",
    link: "/wiki/Fleet-footed_Ixal",
  },
  {
    name: "Flustered Ixal",
    race: "Ixal",
    link: "/wiki/Flustered_Ixal",
  },
  {
    name: "Frightened Ixal",
    race: "Ixal",
    link: "/wiki/Frightened_Ixal",
  },
  {
    name: "Ixali Chieftain",
    race: "Ixal",
    link: "/wiki/Ixali_Chieftain",
  },
  {
    name: "Tuzal Toltan the Unseen",
    race: "Ixal",
    link: "/wiki/Tuzal_Toltan_the_Unseen",
  },
  {
    name: "Aanu Vanu",
    race: "Vanu_Vanu",
    link: "/wiki/Aanu_Vanu",
    gender: "Male",
  },
  {
    name: "Captured Zundu Youth",
    race: "Vanu_Vanu",
    link: "/wiki/Captured_Zundu_Youth",
    gender: "Male",
  },
  {
    name: "Chief Honu Vanu",
    race: "Vanu_Vanu",
    link: "/wiki/Chief_Honu_Vanu",
    gender: "Male",
  },
  {
    name: "Conu Vanu",
    race: "Vanu_Vanu",
    link: "/wiki/Conu_Vanu",
    gender: "Male",
  },
  {
    name: "Cowering Zundu",
    race: "Vanu_Vanu",
    link: "/wiki/Cowering_Zundu",
    gender: "Male",
  },
  {
    name: "Eenu Vanu",
    race: "Vanu_Vanu",
    link: "/wiki/Eenu_Vanu",
    gender: "Male",
  },
  {
    name: "Ganu Vali",
    race: "Vanu_Vanu",
    link: "/wiki/Ganu_Vali",
    gender: "Female",
  },
  {
    name: "Ginu Vanu",
    race: "Vanu_Vanu",
    link: "/wiki/Ginu_Vanu",
    gender: "Male",
  },
  {
    name: "Gona Vanu",
    race: "Vanu_Vanu",
    link: "/wiki/Gona_Vanu",
    gender: "Male",
  },
  {
    name: "Guna Vanu",
    race: "Vanu_Vanu",
    link: "/wiki/Guna_Vanu",
    gender: "Male",
  },
  {
    name: "Gundu Youth",
    race: "Vanu_Vanu",
    link: "/wiki/Gundu_Youth",
  },
  {
    name: "Gunu Vanu",
    race: "Vanu_Vanu",
    link: "/wiki/Gunu_Vanu",
    gender: "Male",
  },
  {
    name: "Hidden Zundu Youth",
    race: "Vanu_Vanu",
    link: "/wiki/Hidden_Zundu_Youth",
  },
  {
    name: "Hinu Vali",
    race: "Vanu_Vanu",
    link: "/wiki/Hinu_Vali",
    gender: "Female",
  },
  {
    name: "Kunu Vali",
    race: "Vanu_Vanu",
    link: "/wiki/Kunu_Vali",
    gender: "Female",
  },
  {
    name: "Linu Vali",
    race: "Vanu_Vanu",
    link: "/wiki/Linu_Vali",
    gender: "Female",
  },
  {
    name: "Linu Vanu",
    race: "Vanu_Vanu",
    link: "/wiki/Linu_Vanu",
    gender: "Male",
  },
  {
    name: "Lonu Vanu",
    race: "Vanu_Vanu",
    link: "/wiki/Lonu_Vanu",
    gender: "Male",
  },
  {
    name: "Luna Vanu",
    race: "Vanu_Vanu",
    link: "/wiki/Luna_Vanu",
  },
  {
    name: "Muna Vanu",
    race: "Vanu_Vanu",
    link: "/wiki/Muna_Vanu",
    gender: "Male",
  },
  {
    name: "Ranu Vali",
    race: "Vanu_Vanu",
    link: "/wiki/Ranu_Vali",
    gender: "Female",
  },
  {
    name: "Raving Vundu",
    race: "Vanu_Vanu",
    link: "/wiki/Raving_Vundu",
  },
  {
    name: "Ronu Vali",
    race: "Vanu_Vanu",
    link: "/wiki/Ronu_Vali",
    gender: "Female",
  },
  {
    name: "Sanu Vanu",
    race: "Vanu_Vanu",
    link: "/wiki/Sanu_Vanu",
    gender: "Male",
  },
  {
    name: "Sonu Vanu",
    race: "Vanu_Vanu",
    link: "/wiki/Sonu_Vanu",
    gender: "Male",
  },
  {
    name: "Tona Vanu",
    race: "Vanu_Vanu",
    link: "/wiki/Tona_Vanu",
    gender: "Male",
  },
  {
    name: "Vanu Elder",
    race: "Vanu_Vanu",
    link: "/wiki/Vanu_Elder",
  },
  {
    name: "Vanu Scout",
    race: "Vanu_Vanu",
    link: "/wiki/Vanu_Scout",
  },
  {
    name: "Vundu Brute",
    race: "Vanu_Vanu",
    link: "/wiki/Vundu_Brute",
    gender: "Male",
  },
  {
    name: "Vundu Cloudfisher",
    race: "Vanu_Vanu",
    link: "/wiki/Vundu_Cloudfisher",
  },
  {
    name: "Vundu Dancer",
    race: "Vanu_Vanu",
    link: "/wiki/Vundu_Dancer",
  },
  {
    name: "Zundu Cloudfisher",
    race: "Vanu_Vanu",
    link: "/wiki/Zundu_Cloudfisher",
  },
  {
    name: "Zundu Sell-it",
    race: "Vanu_Vanu",
    link: "/wiki/Zundu_Sell-it",
  },
  {
    name: "Astute Vath",
    race: "Gnath",
    link: "/wiki/Astute_Vath",
    gender: "Male",
  },
  {
    name: "Cibleroit",
    race: "Gnath",
    link: "/wiki/Cibleroit",
    gender: "Male",
  },
  {
    name: "Gnath Drone",
    race: "Gnath",
    link: "/wiki/Gnath_Drone",
  },
  {
    name: "The Hungerer",
    race: "Gnath",
    link: "/wiki/The_Hungerer",
  },
  {
    name: "Vath Artisan",
    race: "Gnath",
    link: "/wiki/Vath_Artisan",
  },
  {
    name: "Vath Chronicler",
    race: "Gnath",
    link: "/wiki/Vath_Chronicler",
  },
  {
    name: "Vath Deftarm",
    race: "Gnath",
    link: "/wiki/Vath_Deftarm",
    gender: "Male",
  },
  {
    name: "Vath Fleetfoot",
    race: "Gnath",
    link: "/wiki/Vath_Fleetfoot",
    gender: "Male",
  },
  {
    name: "Vath Storyteller",
    race: "Gnath",
    link: "/wiki/Vath_Storyteller",
    gender: "Male",
  },
  {
    name: "Vath Vendor",
    race: "Gnath",
    link: "/wiki/Vath_Vendor",
  },
  {
    name: "Voracious Vath",
    race: "Gnath",
    link: "/wiki/Voracious_Vath",
  },
  {
    name: "Wandering Gnath",
    race: "Gnath",
    link: "/wiki/Wandering_Gnath",
  },
  {
    name: "Choir Moogle",
    race: "Moogle",
    link: "/wiki/Choir_Moogle",
  },
  {
    name: "Commoving Moogle",
    race: "Moogle",
    link: "/wiki/Commoving_Moogle",
  },
  {
    name: "Delivery Moogle",
    race: "Moogle",
    link: "/wiki/Delivery_Moogle",
  },
  {
    name: "Deputy Postmoogle",
    race: "Moogle",
    link: "/wiki/Deputy_Postmoogle",
    gender: "Male",
  },
  {
    name: "Emasculated Moogle",
    race: "Moogle",
    link: "/wiki/Emasculated_Moogle",
  },
  {
    name: "Emptier of Purses",
    race: "Moogle",
    link: "/wiki/Emptier_of_Purses",
  },
  {
    name: "Glimpsing Moogle",
    race: "Moogle",
    link: "/wiki/Glimpsing_Moogle",
  },
  {
    name: "Gossamer Moogle",
    race: "Moogle",
    link: "/wiki/Gossamer_Moogle",
    gender: "Male",
  },
  {
    name: "Hurdy",
    race: "Moogle",
    link: "/wiki/Hurdy",
  },
  {
    name: "Itinerant Moogle",
    race: "Moogle",
    link: "/wiki/Itinerant_Moogle",
  },
  {
    name: "Kupcha Kupa",
    race: "Moogle",
    link: "/wiki/Kupcha_Kupa",
  },
  {
    name: "Kupdi Koop",
    race: "Moogle",
    link: "/wiki/Kupdi_Koop",
  },
  {
    name: "Kupka Kopp",
    race: "Moogle",
    link: "/wiki/Kupka_Kopp",
  },
  {
    name: "Kupka Kupp",
    race: "Moogle",
    link: "/wiki/Kupka_Kupp",
    gender: "Male",
  },
  {
    name: "Kupli Kipp",
    race: "Moogle",
    link: "/wiki/Kupli_Kipp",
  },
  {
    name: "Kupli Kuki",
    race: "Moogle",
    link: "/wiki/Kupli_Kuki",
  },
  {
    name: "Kuplo Kopp",
    race: "Moogle",
    link: "/wiki/Kuplo_Kopp",
    gender: "Male",
  },
  {
    name: "Kuplu Kopo",
    race: "Moogle",
    link: "/wiki/Kuplu_Kopo",
  },
  {
    name: "Kuplu Kumu",
    race: "Moogle",
    link: "/wiki/Kuplu_Kumu",
  },
  {
    name: "Kupta Kapa",
    race: "Moogle",
    link: "/wiki/Kupta_Kapa",
  },
  {
    name: "Matted Moogle",
    race: "Moogle",
    link: "/wiki/Matted_Moogle",
  },
  {
    name: "Modish Moogle",
    race: "Moogle",
    link: "/wiki/Modish_Moogle",
  },
  {
    name: "Moggie",
    race: "Moogle",
    link: "/wiki/Moggie",
  },
  {
    name: "Moggzia",
    race: "Moogle",
    link: "/wiki/Moggzia",
  },
  {
    name: "Moghan",
    race: "Moogle",
    link: "/wiki/Moghan",
    gender: "Male",
  },
  {
    name: "Moglin",
    race: "Moogle",
    link: "/wiki/Moglin",
    gender: "Male",
  },
  {
    name: "Mogloo",
    race: "Moogle",
    link: "/wiki/Mogloo",
  },
  {
    name: "Mogmill",
    race: "Moogle",
    link: "/wiki/Mogmill",
  },
  {
    name: "Mogmug",
    race: "Moogle",
    link: "/wiki/Mogmug",
    gender: "Male",
  },
  {
    name: "Mogomo",
    race: "Moogle",
    link: "/wiki/Mogomo",
  },
  {
    name: "Mogoosh the Misbehaving (NPC)",
    race: "Moogle",
    link: "/wiki/Mogoosh_the_Misbehaving_(NPC)",
  },
  {
    name: "Mogpo the Magnificent",
    race: "Moogle",
    link: "/wiki/Mogpo_the_Magnificent",
  },
  {
    name: "Mogret",
    race: "Moogle",
    link: "/wiki/Mogret",
    gender: "Female",
  },
  {
    name: "Mogsy",
    race: "Moogle",
    link: "/wiki/Mogsy",
  },
  {
    name: "Mogtoe",
    race: "Moogle",
    link: "/wiki/Mogtoe",
  },
  {
    name: "Mogule",
    race: "Moogle",
    link: "/wiki/Mogule",
  },
  {
    name: "Mogwin",
    race: "Moogle",
    link: "/wiki/Mogwin",
    gender: "Male",
  },
  {
    name: "Montblanc",
    race: "Moogle",
    link: "/wiki/Montblanc",
  },
  {
    name: "Moody Moogle",
    race: "Moogle",
    link: "/wiki/Moody_Moogle",
  },
  {
    name: "Moogle (NPC)",
    race: "Moogle",
    link: "/wiki/Moogle_(NPC)",
  },
  {
    name: "Mouthing-off Moogle",
    race: "Moogle",
    link: "/wiki/Mouthing-off_Moogle",
  },
  {
    name: "Muddled Moogle",
    race: "Moogle",
    link: "/wiki/Muddled_Moogle",
  },
  {
    name: "Portly Moogle",
    race: "Moogle",
    link: "/wiki/Portly_Moogle",
  },
  {
    name: "Pukno Poki",
    race: "Moogle",
    link: "/wiki/Pukno_Poki",
    gender: "Female",
  },
  {
    name: "Pukty Piko",
    race: "Moogle",
    link: "/wiki/Pukty_Piko",
    gender: "Female",
  },
  {
    name: "Pukwa Pika",
    race: "Moogle",
    link: "/wiki/Pukwa_Pika",
    gender: "Female",
  },
  {
    name: "Whiskerwall Kupdi Koop",
    race: "Moogle",
    link: "/wiki/Whiskerwall_Kupdi_Koop",
    gender: "Male",
  },
  {
    name: "Affable Kojin",
    race: "Kojin",
    link: "/wiki/Affable_Kojin",
    gender: "Male",
  },
  {
    name: "Blue Artisan",
    race: "Kojin",
    link: "/wiki/Blue_Artisan",
    gender: "Male",
  },
  {
    name: "Blue Falcon Porter",
    race: "Kojin",
    link: "/wiki/Blue_Falcon_Porter",
  },
  {
    name: "Blue Kojin Emissary",
    race: "Kojin",
    link: "/wiki/Blue_Kojin_Emissary",
  },
  {
    name: "Blue Mender",
    race: "Kojin",
    link: "/wiki/Blue_Mender",
  },
  {
    name: "Blue Merchant",
    race: "Kojin",
    link: "/wiki/Blue_Merchant",
  },
  {
    name: "Candid Kojin",
    race: "Kojin",
    link: "/wiki/Candid_Kojin",
    gender: "Male",
  },
  {
    name: "Cranky Kojin",
    race: "Kojin",
    link: "/wiki/Cranky_Kojin",
    gender: "Female",
  },
  {
    name: "Alpa",
    race: "Ananta",
    link: "/wiki/Alpa",
    gender: "Female",
  },
  {
    name: "Anamika",
    race: "Ananta",
    link: "/wiki/Anamika",
    gender: "Female",
  },
  {
    name: "Ananta Battlemaid",
    race: "Ananta",
    link: "/wiki/Ananta_Battlemaid",
    gender: "Female",
  },
  {
    name: "Ananta Instructor",
    race: "Ananta",
    link: "/wiki/Ananta_Instructor",
    gender: "Female",
  },
  {
    name: "Ananta Junkmonger (Player Housing)",
    race: "Ananta",
    link: "/wiki/Ananta_Junkmonger_(Player_Housing)",
    gender: "Female",
  },
  {
    name: "Ananta Maidservant",
    race: "Ananta",
    link: "/wiki/Ananta_Maidservant",
    gender: "Female",
  },
  {
    name: "Ananta Material Supplier",
    race: "Ananta",
    link: "/wiki/Ananta_Material_Supplier",
    gender: "Female",
  },
  {
    name: "Ananta Mender",
    race: "Ananta",
    link: "/wiki/Ananta_Mender",
    gender: "Female",
  },
  {
    name: "Ananta Recruit",
    race: "Ananta",
    link: "/wiki/Ananta_Recruit",
    gender: "Female",
  },
  {
    name: "Ananta Sentry",
    race: "Ananta",
    link: "/wiki/Ananta_Sentry",
    gender: "Female",
  },
  {
    name: "Ananta Whispermaid",
    race: "Ananta",
    link: "/wiki/Ananta_Whispermaid",
    gender: "Female",
  },
  {
    name: "Anuraga",
    race: "Ananta",
    link: "/wiki/Anuraga",
    gender: "Female",
  },
  {
    name: "Blessed Mender",
    race: "Ananta",
    link: "/wiki/Blessed_Mender",
    gender: "Female",
  },
  {
    name: "Blessed Merchant",
    race: "Ananta",
    link: "/wiki/Blessed_Merchant",
    gender: "Female",
  },
  {
    name: "Carma",
    race: "Ananta",
    link: "/wiki/Carma",
    gender: "Female",
  },
  {
    name: "Chandani",
    race: "Ananta",
    link: "/wiki/Chandani",
    gender: "Female",
  },
  {
    name: "Dakshina",
    race: "Ananta",
    link: "/wiki/Dakshina",
    gender: "Female",
  },
  {
    name: "Dhanna",
    race: "Ananta",
    link: "/wiki/Dhanna",
    gender: "Female",
  },
  {
    name: "Eshana",
    race: "Ananta",
    link: "/wiki/Eshana",
    gender: "Female",
  },
  {
    name: "Garima",
    race: "Ananta",
    link: "/wiki/Garima",
    gender: "Female",
  },
  {
    name: "Gitika",
    race: "Ananta",
    link: "/wiki/Gitika",
    gender: "Female",
  },
  {
    name: "Affable Namazu",
    race: "Namazu",
    link: "/wiki/Affable_Namazu",
  },
  {
    name: "Catty Namazu",
    race: "Namazu",
    link: "/wiki/Catty_Namazu",
  },
  {
    name: "Earnest Namazu",
    race: "Namazu",
    link: "/wiki/Earnest_Namazu",
  },
  {
    name: "First Namazu Disciple",
    race: "Namazu",
    link: "/wiki/First_Namazu_Disciple",
    gender: "Male",
  },
  {
    name: "Floundering Namazu",
    race: "Namazu",
    link: "/wiki/Floundering_Namazu",
    gender: "Male",
  },
  {
    name: "Fried Namazu",
    race: "Namazu",
    link: "/wiki/Fried_Namazu",
  },
  {
    name: "Gyodo",
    race: "Namazu",
    link: "/wiki/Gyodo",
  },
  {
    name: "Aenc Uin",
    race: "Pixie",
    link: "/wiki/Aenc_Uin",
  },
  {
    name: "An Iala",
    race: "Pixie",
    link: "/wiki/An_Iala",
  },
  {
    name: "An Lad",
    race: "Pixie",
    link: "/wiki/An_Lad",
  },
  {
    name: "Art-loving Pixie",
    race: "Pixie",
    link: "/wiki/Art-loving_Pixie",
  },
  {
    name: "Beq Thon",
    race: "Pixie",
    link: "/wiki/Beq_Thon",
  },
  {
    name: "Chipper Pixie",
    race: "Pixie",
    link: "/wiki/Chipper_Pixie",
  },
  {
    name: "Concealed Pixie",
    race: "Pixie",
    link: "/wiki/Concealed_Pixie",
  },
  {
    name: "Covetous Pixie",
    race: "Pixie",
    link: "/wiki/Covetous_Pixie",
  },
  {
    name: "Discovered Pixie",
    race: "Pixie",
    link: "/wiki/Discovered_Pixie",
  },
  {
    name: "Dispirited Pixie",
    race: "Pixie",
    link: "/wiki/Dispirited_Pixie",
  },
  {
    name: "Exuberant Pixie",
    race: "Pixie",
    link: "/wiki/Exuberant_Pixie",
  },
  {
    name: "Feo Ul",
    race: "Pixie",
    link: "/wiki/Feo_Ul",
  },
  {
    name: "Flower-picking Pixie",
    race: "Pixie",
    link: "/wiki/Flower-picking_Pixie",
  },
  {
    name: "Gossipy Pixie",
    race: "Pixie",
    link: "/wiki/Gossipy_Pixie",
  },
  {
    name: "Green-thumbed Pixie",
    race: "Pixie",
    link: "/wiki/Green-thumbed_Pixie",
  },
  {
    name: "Sheep-obsessed Pixie",
    race: "Pixie",
    link: "/wiki/Sheep-obsessed_Pixie",
  },
  {
    name: "Sul Lad",
    race: "Pixie",
    link: "/wiki/Sul_Lad",
  },
  {
    name: "Chaqurl Qhotl",
    race: "Qiqirn",
    link: "/wiki/Chaqurl_Qhotl",
    gender: "Male",
  },
  {
    name: "Chuchuroon",
    race: "Qiqirn",
    link: "/wiki/Chuchuroon",
    gender: "Male",
  },
  {
    name: "Deflated Steward",
    race: "Qiqirn",
    link: "/wiki/Deflated_Steward",
  },
  {
    name: "Ferry Skipper (Jijiroon's Trading Post)",
    race: "Qiqirn",
    link: "/wiki/Ferry_Skipper_(Jijiroon%27s_Trading_Post)",
  },
  {
    name: "Ferry Skipper (Memeroon's Trading Post)",
    race: "Qiqirn",
    link: "/wiki/Ferry_Skipper_(Memeroon%27s_Trading_Post)",
  },
  {
    name: "Gegeroon",
    race: "Qiqirn",
    link: "/wiki/Gegeroon",
    gender: "Male",
  },
  {
    name: "Jojoroon",
    race: "Qiqirn",
    link: "/wiki/Jojoroon",
  },
  {
    name: "Junkmonger (Jijiroon's Trading Post)",
    race: "Qiqirn",
    link: "/wiki/Junkmonger_(Jijiroon%27s_Trading_Post)",
  },
  {
    name: "Junkmonger (Memeroon's Trading Post)",
    race: "Qiqirn",
    link: "/wiki/Junkmonger_(Memeroon%27s_Trading_Post)",
  },
  {
    name: "Junkmonger Nonoroon",
    race: "Qiqirn",
    link: "/wiki/Junkmonger_Nonoroon",
  },
  {
    name: "Memeroon",
    race: "Qiqirn",
    link: "/wiki/Memeroon",
    gender: "Male",
  },
  {
    name: "Qhoterl Pasol",
    race: "Qiqirn",
    link: "/wiki/Qhoterl_Pasol",
  },
  {
    name: "Qiqirn Guide",
    race: "Qiqirn",
    link: "/wiki/Qiqirn_Guide",
  },
  {
    name: "Qiqirn Rat",
    race: "Qiqirn",
    link: "/wiki/Qiqirn_Rat",
  },
  {
    name: "Abdhi",
    race: "Matanga",
    link: "/wiki/Abdhi",
    gender: "Male",
  },
  {
    name: "Acala",
    race: "Matanga",
    link: "/wiki/Acala",
    gender: "Male",
  },
  {
    name: "Ambhas",
    race: "Matanga",
    link: "/wiki/Ambhas",
    gender: "Female",
  },
  {
    name: "Amra (NPC)",
    race: "Matanga",
    link: "/wiki/Amra_(NPC)",
    gender: "Male",
  },
  {
    name: "Animated Alchemist",
    race: "Matanga",
    link: "/wiki/Animated_Alchemist",
    gender: "Male",
  },
  {
    name: "Anxious Provider",
    race: "Matanga",
    link: "/wiki/Anxious_Provider",
    gender: "Female",
  },
  {
    name: "Arkasodara Alchemist",
    race: "Matanga",
    link: "/wiki/Arkasodara_Alchemist",
    gender: "Female",
  },
  {
    name: "Arkasodara Youth",
    race: "Matanga",
    link: "/wiki/Arkasodara_Youth",
    gender: "Male",
  },
  {
    name: "Ayas",
    race: "Matanga",
    link: "/wiki/Ayas",
    gender: "Male",
  },
  {
    name: "Eager Steward",
    race: "Matanga",
    link: "/wiki/Eager_Steward",
    gender: "Male",
  },
  {
    name: "Esurient Arkasodara",
    race: "Matanga",
    link: "/wiki/Esurient_Arkasodara",
    gender: "Male",
  },
  {
    name: "Fretful Arkasodara",
    race: "Matanga",
    link: "/wiki/Fretful_Arkasodara",
    gender: "Female",
  },
  {
    name: "Ghasa",
    race: "Matanga",
    link: "/wiki/Ghasa",
    gender: "Male",
  },
  {
    name: "Harried Rider",
    race: "Matanga",
    link: "/wiki/Harried_Rider",
    gender: "Male",
  },
  {
    name: "Industrious Resident",
    race: "Matanga",
    link: "/wiki/Industrious_Resident",
    gender: "Female",
  },
  {
    name: "Isu",
    race: "Matanga",
    link: "/wiki/Isu",
    gender: "Female",
  },
  {
    name: "Jalamuc",
    race: "Matanga",
    link: "/wiki/Jalamuc",
    gender: "Male",
  },
  {
    name: "Junkmonger (The Great Work)",
    race: "Matanga",
    link: "/wiki/Junkmonger_(The_Great_Work)",
    gender: "Male",
  },
  {
    name: "Kamala",
    race: "Matanga",
    link: "/wiki/Kamala",
    gender: "Female",
  },
  {
    name: "Kancana",
    race: "Matanga",
    link: "/wiki/Kancana",
    gender: "Female",
  },
  {
    name: "Khanga",
    race: "Matanga",
    link: "/wiki/Khanga",
    gender: "Male",
  },
  {
    name: "Kunta",
    race: "Matanga",
    link: "/wiki/Kunta",
    gender: "Male",
  },
  {
    name: "Kusuma",
    race: "Matanga",
    link: "/wiki/Kusuma",
    gender: "Female",
  },
  {
    name: "Maru",
    race: "Matanga",
    link: "/wiki/Maru",
    gender: "Male",
  },
  {
    name: "Matsya",
    race: "Matanga",
    link: "/wiki/Matsya",
    gender: "Male",
  },
  {
    name: "Nadi",
    race: "Matanga",
    link: "/wiki/Nadi",
    gender: "Female",
  },
  {
    name: "Nervous Rider",
    race: "Matanga",
    link: "/wiki/Nervous_Rider",
    gender: "Male",
  },
  {
    name: "Nidhana",
    race: "Matanga",
    link: "/wiki/Nidhana",
    gender: "Female",
  },
  {
    name: "Peaceful Resident",
    race: "Matanga",
    link: "/wiki/Peaceful_Resident",
    gender: "Male",
  },
  {
    name: "Pondering Resident",
    race: "Matanga",
    link: "/wiki/Pondering_Resident",
    gender: "Male",
  },
  {
    name: "Standoffish Stonemason",
    race: "Matanga",
    link: "/wiki/Standoffish_Stonemason",
    gender: "Male",
  },
  {
    name: "Sula",
    race: "Matanga",
    link: "/wiki/Sula",
    gender: "Female",
  },
  {
    name: "Trna",
    race: "Matanga",
    link: "/wiki/Trna",
    gender: "Female",
  },
  {
    name: "Udadhi",
    race: "Matanga",
    link: "/wiki/Udadhi",
    gender: "Male",
  },
  {
    name: "Utpala",
    race: "Matanga",
    link: "/wiki/Utpala",
    gender: "Female",
  },
  {
    name: "Vata",
    race: "Matanga",
    link: "/wiki/Vata",
    gender: "Male",
  },
  {
    name: "Wizened Arkasodara",
    race: "Matanga",
    link: "/wiki/Wizened_Arkasodara",
    gender: "Male",
  },
  {
    name: "Aberrant Savor-seeking Unit",
    race: "Omicron",
    link: "/wiki/Aberrant_Savor-seeking_Unit",
  },
  {
    name: "Eager Support Unit",
    race: "Omicron",
    link: "/wiki/Eager_Support_Unit",
  },
  {
    name: "Food Processing Unit",
    race: "Omicron",
    link: "/wiki/Food_Processing_Unit",
  },
  {
    name: "M-017",
    race: "Omicron",
    link: "/wiki/M-017",
  },
  {
    name: "M-032",
    race: "Omicron",
    link: "/wiki/M-032",
  },
  {
    name: "M-051",
    race: "Omicron",
    link: "/wiki/M-051",
  },
  {
    name: "M-097",
    race: "Omicron",
    link: "/wiki/M-097",
  },
  {
    name: "M-104",
    race: "Omicron",
    link: "/wiki/M-104",
  },
  {
    name: "Merchant & Mender (Base Omicron)",
    race: "Omicron",
    link: "/wiki/Merchant_%26_Mender_(Base_Omicron)",
  },
  {
    name: "N-0055",
    race: "Omicron",
    link: "/wiki/N-0055",
  },
  {
    name: "N-0253",
    race: "Omicron",
    link: "/wiki/N-0253",
  },
  {
    name: "N-1499",
    race: "Omicron",
    link: "/wiki/N-1499",
  },
  {
    name: "N-2174",
    race: "Omicron",
    link: "/wiki/N-2174",
  },
  {
    name: "N-4486",
    race: "Omicron",
    link: "/wiki/N-4486",
  },
  {
    name: "N-6205",
    race: "Omicron",
    link: "/wiki/N-6205",
  },
  {
    name: "N-7000",
    race: "Omicron",
    link: "/wiki/N-7000",
  },
  {
    name: "Omicron Guard",
    race: "Omicron",
    link: "/wiki/Omicron_Guard",
  },
  {
    name: "Stigma-4",
    race: "Omicron",
    link: "/wiki/Stigma-4",
  },
  {
    name: "Backrix",
    race: "Goblin",
    link: "/wiki/Backrix",
    gender: "Male",
  },
  {
    name: "Boilstox",
    race: "Goblin",
    link: "/wiki/Boilstox",
  },
  {
    name: "Boomshox",
    race: "Goblin",
    link: "/wiki/Boomshox",
    gender: "Female",
  },
  {
    name: "Brayflox Alltalks",
    race: "Goblin",
    link: "/wiki/Brayflox_Alltalks",
    gender: "Female",
  },
  {
    name: "Cheepchix",
    race: "Goblin",
    link: "/wiki/Cheepchix",
    gender: "Male",
  },
  {
    name: "Clicklox",
    race: "Goblin",
    link: "/wiki/Clicklox",
    gender: "Male",
  },
  {
    name: "Dripwix",
    race: "Goblin",
    link: "/wiki/Dripwix",
    gender: "Male",
  },
  {
    name: "Drydox",
    race: "Goblin",
    link: "/wiki/Drydox",
    gender: "Female",
  },
  {
    name: "Feltsmox",
    race: "Goblin",
    link: "/wiki/Feltsmox",
    gender: "Female",
  },
  {
    name: "Gangly Goblin",
    race: "Goblin",
    link: "/wiki/Gangly_Goblin",
    gender: "Male",
  },
  {
    name: "Goblin Coalshifter",
    race: "Goblin",
    link: "/wiki/Goblin_Coalshifter",
    gender: "Male",
  },
  {
    name: "Goblin Guide",
    race: "Goblin",
    link: "/wiki/Goblin_Guide",
    gender: "Male",
  },
  {
    name: "Goblin Herbalist",
    race: "Goblin",
    link: "/wiki/Goblin_Herbalist",
    gender: "Male",
  },
  {
    name: "Goblin Merchant",
    race: "Goblin",
    link: "/wiki/Goblin_Merchant",
    gender: "Male",
  },
  {
    name: "Goblin Pathfinder",
    race: "Goblin",
    link: "/wiki/Goblin_Pathfinder",
  },
  {
    name: "Goblin Scavenger",
    race: "Goblin",
    link: "/wiki/Goblin_Scavenger",
  },
  {
    name: "Goblin Tinker",
    race: "Goblin",
    link: "/wiki/Goblin_Tinker",
  },
  {
    name: "Goblin Trader",
    race: "Goblin",
    link: "/wiki/Goblin_Trader",
    gender: "Male",
  },
  {
    name: "Gobwatch",
    race: "Goblin",
    link: "/wiki/Gobwatch",
  },
  {
    name: "Goldwox",
    race: "Goblin",
    link: "/wiki/Goldwox",
    gender: "Female",
  },
  {
    name: "Grinmox",
    race: "Goblin",
    link: "/wiki/Grinmox",
    gender: "Female",
  },
  {
    name: "Guttrix Silverpicks",
    race: "Goblin",
    link: "/wiki/Guttrix_Silverpicks",
    gender: "Male",
  },
  {
    name: "Halfsix",
    race: "Goblin",
    link: "/wiki/Halfsix",
    gender: "Male",
  },
  {
    name: "Holepix",
    race: "Goblin",
    link: "/wiki/Holepix",
    gender: "Male",
  },
  {
    name: "Loudjox",
    race: "Goblin",
    link: "/wiki/Loudjox",
    gender: "Female",
  },
  {
    name: "Mutamix Bubblypots",
    race: "Goblin",
    link: "/wiki/Mutamix_Bubblypots",
    gender: "Male",
  },
  {
    name: "Poofchox",
    race: "Goblin",
    link: "/wiki/Poofchox",
    gender: "Female",
  },
  {
    name: "Redbrix",
    race: "Goblin",
    link: "/wiki/Redbrix",
    gender: "Male",
  },
  {
    name: "Roundrox",
    race: "Goblin",
    link: "/wiki/Roundrox",
    gender: "Female",
  },
  {
    name: "Slimthix",
    race: "Goblin",
    link: "/wiki/Slimthix",
    gender: "Male",
  },
  {
    name: "Slowfix",
    race: "Goblin",
    link: "/wiki/Slowfix",
    gender: "Male",
  },
  {
    name: "Smacklix",
    race: "Goblin",
    link: "/wiki/Smacklix",
    gender: "Female",
  },
  {
    name: "Softknox",
    race: "Goblin",
    link: "/wiki/Softknox",
    gender: "Female",
  },
  {
    name: "Stackblox",
    race: "Goblin",
    link: "/wiki/Stackblox",
    gender: "Female",
  },
  {
    name: "Startled Goblin",
    race: "Goblin",
    link: "/wiki/Startled_Goblin",
    gender: "Male",
  },
  {
    name: "Stickqix",
    race: "Goblin",
    link: "/wiki/Stickqix",
    gender: "Male",
  },
  {
    name: "Stopklox Grislyfist",
    race: "Goblin",
    link: "/wiki/Stopklox_Grislyfist",
    gender: "Female",
  },
  {
    name: "Tapklix",
    race: "Goblin",
    link: "/wiki/Tapklix",
    gender: "Male",
  },
  {
    name: "Tocktix",
    race: "Goblin",
    link: "/wiki/Tocktix",
    gender: "Male",
  },
  {
    name: "Woolnix",
    race: "Goblin",
    link: "/wiki/Woolnix",
    gender: "Male",
  },
  {
    name: "Amiable Youth",
    race: "Mamool_Ja",
    link: "/wiki/Amiable_Youth",
  },
  {
    name: "Angered Soldier",
    race: "Mamool_Ja",
    link: "/wiki/Angered_Soldier",
  },
  {
    name: "Bakool Ja",
    race: "Mamool_Ja",
    link: "/wiki/Bakool_Ja",
  },
  {
    name: "Bebeel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Bebeel_Ja",
  },
  {
    name: "Beeril Ja",
    race: "Mamool_Ja",
    link: "/wiki/Beeril_Ja",
    gender: "Female",
  },
  {
    name: "Belligerent Boonewa",
    race: "Mamool_Ja",
    link: "/wiki/Belligerent_Boonewa",
  },
  {
    name: "Beqoll Ja",
    race: "Mamool_Ja",
    link: "/wiki/Beqoll_Ja",
    gender: "Male",
  },
  {
    name: "Bladewise Hoobigo",
    race: "Mamool_Ja",
    link: "/wiki/Bladewise_Hoobigo",
  },
  {
    name: "Blue-scaled Hoobigo Child",
    race: "Mamool_Ja",
    link: "/wiki/Blue-scaled_Hoobigo_Child",
    gender: "Male",
  },
  {
    name: "Ceetol Ja",
    race: "Mamool_Ja",
    link: "/wiki/Ceetol_Ja",
  },
  {
    name: "Chatty Hoobigo",
    race: "Mamool_Ja",
    link: "/wiki/Chatty_Hoobigo",
    gender: "Female",
  },
  {
    name: "Considering Citizen",
    race: "Mamool_Ja",
    link: "/wiki/Considering_Citizen",
    gender: "Female",
  },
  {
    name: "Coughing Doppro",
    race: "Mamool_Ja",
    link: "/wiki/Coughing_Doppro",
  },
  {
    name: "Cullaal Ja",
    race: "Mamool_Ja",
    link: "/wiki/Cullaal_Ja",
  },
  {
    name: "Curt Doppro",
    race: "Mamool_Ja",
    link: "/wiki/Curt_Doppro",
  },
  {
    name: "Dazed Citizen (No Time for Tears)",
    race: "Mamool_Ja",
    link: "/wiki/Dazed_Citizen_(No_Time_for_Tears)",
    gender: "Male",
  },
  {
    name: "Despondent Man",
    race: "Mamool_Ja",
    link: "/wiki/Despondent_Man",
    gender: "Male",
  },
  {
    name: "Determined Doppro",
    race: "Mamool_Ja",
    link: "/wiki/Determined_Doppro",
    gender: "Male",
  },
  {
    name: "Dignified Dancer",
    race: "Mamool_Ja",
    link: "/wiki/Dignified_Dancer",
  },
  {
    name: "Dignified Lady (City of Silence)",
    race: "Mamool_Ja",
    link: "/wiki/Dignified_Lady_(City_of_Silence)",
    gender: "Female",
  },
  {
    name: "Diinal Ja",
    race: "Mamool_Ja",
    link: "/wiki/Diinal_Ja",
  },
  {
    name: "Dirigible Attendant (Yak T'el)",
    race: "Mamool_Ja",
    link: "/wiki/Dirigible_Attendant_(Yak_T%27el)",
  },
  {
    name: "Drained Patrolman",
    race: "Mamool_Ja",
    link: "/wiki/Drained_Patrolman",
  },
  {
    name: "Dubious Doppro",
    race: "Mamool_Ja",
    link: "/wiki/Dubious_Doppro",
  },
  {
    name: "Dumbfounded Farmer",
    race: "Mamool_Ja",
    link: "/wiki/Dumbfounded_Farmer",
    gender: "Male",
  },
  {
    name: "Eager Elder",
    race: "Mamool_Ja",
    link: "/wiki/Eager_Elder",
  },
  {
    name: "Eefil Ja",
    race: "Mamool_Ja",
    link: "/wiki/Eefil_Ja",
    gender: "Female",
  },
  {
    name: "Flustered Citizen",
    race: "Mamool_Ja",
    link: "/wiki/Flustered_Citizen",
    gender: "Male",
  },
  {
    name: "Frazzled Boonewa",
    race: "Mamool_Ja",
    link: "/wiki/Frazzled_Boonewa",
  },
  {
    name: "Gentle Senior",
    race: "Mamool_Ja",
    link: "/wiki/Gentle_Senior",
    gender: "Female",
  },
  {
    name: "Goteel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Goteel_Ja",
    gender: "Male",
  },
  {
    name: "Gotoll Ja",
    race: "Mamool_Ja",
    link: "/wiki/Gotoll_Ja",
    gender: "Male",
  },
  {
    name: "Grove Worker",
    race: "Mamool_Ja",
    link: "/wiki/Grove_Worker",
  },
  {
    name: "Gruff Resident",
    race: "Mamool_Ja",
    link: "/wiki/Gruff_Resident",
  },
  {
    name: "Gulool Ja",
    race: "Mamool_Ja",
    link: "/wiki/Gulool_Ja",
  },
  {
    name: "Gulool Ja Ja",
    race: "Mamool_Ja",
    link: "/wiki/Gulool_Ja_Ja",
  },
  {
    name: "Hakeel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Hakeel_Ja",
  },
  {
    name: "Hapoll Ja",
    race: "Mamool_Ja",
    link: "/wiki/Hapoll_Ja",
    gender: "Male",
  },
  {
    name: "Harried Handler",
    race: "Mamool_Ja",
    link: "/wiki/Harried_Handler",
  },
  {
    name: "Heemil Ja",
    race: "Mamool_Ja",
    link: "/wiki/Heemil_Ja",
    gender: "Female",
  },
  {
    name: "Hesitant Handler",
    race: "Mamool_Ja",
    link: "/wiki/Hesitant_Handler",
  },
  {
    name: "Hiiral Ja",
    race: "Mamool_Ja",
    link: "/wiki/Hiiral_Ja",
    gender: "Male",
  },
  {
    name: "Hoobigo Guardian",
    race: "Mamool_Ja",
    link: "/wiki/Hoobigo_Guardian",
  },
  {
    name: "Hoobigo Lancer",
    race: "Mamool_Ja",
    link: "/wiki/Hoobigo_Lancer",
  },
  {
    name: "Hoobigo Merchant",
    race: "Mamool_Ja",
    link: "/wiki/Hoobigo_Merchant",
    gender: "Male",
  },
  {
    name: "Hoobigo Onlooker",
    race: "Mamool_Ja",
    link: "/wiki/Hoobigo_Onlooker",
    gender: "Female",
  },
  {
    name: "Hoobigo Skipper (Kozama'uka)",
    race: "Mamool_Ja",
    link: "/wiki/Hoobigo_Skipper_(Kozama%27uka)",
  },
  {
    name: "Hoobigo Skipper (Tuliyollal)",
    race: "Mamool_Ja",
    link: "/wiki/Hoobigo_Skipper_(Tuliyollal)",
  },
  {
    name: "Hungry Mamool Ja",
    race: "Mamool_Ja",
    link: "/wiki/Hungry_Mamool_Ja",
  },
  {
    name: "Huvool Ja",
    race: "Mamool_Ja",
    link: "/wiki/Huvool_Ja",
  },
  {
    name: "Idle Boonewa",
    race: "Mamool_Ja",
    link: "/wiki/Idle_Boonewa",
  },
  {
    name: "Kachaal Ja",
    race: "Mamool_Ja",
    link: "/wiki/Kachaal_Ja",
  },
  {
    name: "Kageel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Kageel_Ja",
    gender: "Male",
  },
  {
    name: "Kaqool Ja",
    race: "Mamool_Ja",
    link: "/wiki/Kaqool_Ja",
  },
  {
    name: "Kiishel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Kiishel_Ja",
    gender: "Female",
  },
  {
    name: "Kivaal Ja",
    race: "Mamool_Ja",
    link: "/wiki/Kivaal_Ja",
  },
  {
    name: "Kubeel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Kubeel_Ja",
    gender: "Male",
  },
  {
    name: "Lafaal Ja",
    race: "Mamool_Ja",
    link: "/wiki/Lafaal_Ja",
  },
  {
    name: "Landsguard Gatekeeper",
    race: "Mamool_Ja",
    link: "/wiki/Landsguard_Gatekeeper",
  },
  {
    name: "Liinel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Liinel_Ja",
    gender: "Female",
  },
  {
    name: "Local Merchant (Mamook)",
    race: "Mamool_Ja",
    link: "/wiki/Local_Merchant_(Mamook)",
    gender: "Male",
  },
  {
    name: "Mamool Ja Landsguard",
    race: "Mamool_Ja",
    link: "/wiki/Mamool_Ja_Landsguard",
    gender: "Male",
  },
  {
    name: "Mamool Ja Landsguard (A Notion of Promotion)",
    race: "Mamool_Ja",
    link: "/wiki/Mamool_Ja_Landsguard_(A_Notion_of_Promotion)",
    gender: "Male",
  },
  {
    name: "Mamool Ja Marketeer",
    race: "Mamool_Ja",
    link: "/wiki/Mamool_Ja_Marketeer",
  },
  {
    name: "Maudlin Latool Ja",
    race: "Mamool_Ja",
    link: "/wiki/Maudlin_Latool_Ja",
  },
  {
    name: "Meerel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Meerel_Ja",
    gender: "Female",
  },
  {
    name: "Menacing Mamool Ja",
    race: "Mamool_Ja",
    link: "/wiki/Menacing_Mamool_Ja",
  },
  {
    name: "Mender (Mamook)",
    race: "Mamool_Ja",
    link: "/wiki/Mender_(Mamook)",
    gender: "Female",
  },
  {
    name: "Meticulous Mamool Ja",
    race: "Mamool_Ja",
    link: "/wiki/Meticulous_Mamool_Ja",
  },
  {
    name: "Miilal Ja",
    race: "Mamool_Ja",
    link: "/wiki/Miilal_Ja",
    gender: "Female",
  },
  {
    name: "Miisul Ja",
    race: "Mamool_Ja",
    link: "/wiki/Miisul_Ja",
    gender: "Female",
  },
  {
    name: "Mild-mannered Mamool Ja",
    race: "Mamool_Ja",
    link: "/wiki/Mild-mannered_Mamool_Ja",
  },
  {
    name: "Mireel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Mireel_Ja",
    gender: "Male",
  },
  {
    name: "Mobeel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Mobeel_Ja",
  },
  {
    name: "Mosaal Ja",
    race: "Mamool_Ja",
    link: "/wiki/Mosaal_Ja",
  },
  {
    name: "Mushroom Hunter",
    race: "Mamool_Ja",
    link: "/wiki/Mushroom_Hunter",
  },
  {
    name: "Personable Boonewa",
    race: "Mamool_Ja",
    link: "/wiki/Personable_Boonewa",
    gender: "Female",
  },
  {
    name: "Precocious Mamool Ja",
    race: "Mamool_Ja",
    link: "/wiki/Precocious_Mamool_Ja",
    gender: "Female",
  },
  {
    name: "Prudent Hunter",
    race: "Mamool_Ja",
    link: "/wiki/Prudent_Hunter",
  },
  {
    name: "Pudeel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Pudeel_Ja",
  },
  {
    name: "Quroll Ja",
    race: "Mamool_Ja",
    link: "/wiki/Quroll_Ja",
    gender: "Male",
  },
  {
    name: "Radoll Ja",
    race: "Mamool_Ja",
    link: "/wiki/Radoll_Ja",
  },
  {
    name: "Raholl Ja",
    race: "Mamool_Ja",
    link: "/wiki/Raholl_Ja",
  },
  {
    name: "Retired Mercenary",
    race: "Mamool_Ja",
    link: "/wiki/Retired_Mercenary",
  },
  {
    name: "Rikoll Ja",
    race: "Mamool_Ja",
    link: "/wiki/Rikoll_Ja",
    gender: "Male",
  },
  {
    name: "Ruvoll Ja",
    race: "Mamool_Ja",
    link: "/wiki/Ruvoll_Ja",
    gender: "Male",
  },
  {
    name: "Ryubool Ja",
    race: "Mamool_Ja",
    link: "/wiki/Ryubool_Ja",
  },
  {
    name: "Sajool Ja",
    race: "Mamool_Ja",
    link: "/wiki/Sajool_Ja",
  },
  {
    name: "Sareel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Sareel_Ja",
  },
  {
    name: "Shiidil Ja",
    race: "Mamool_Ja",
    link: "/wiki/Shiidil_Ja",
    gender: "Female",
  },
  {
    name: "Soneel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Soneel_Ja",
    gender: "Male",
  },
  {
    name: "Sorrowful Citizen (Together as One)",
    race: "Mamool_Ja",
    link: "/wiki/Sorrowful_Citizen_(Together_as_One)",
    gender: "Female",
  },
  {
    name: "Stave-bearing Guard",
    race: "Mamool_Ja",
    link: "/wiki/Stave-bearing_Guard",
  },
  {
    name: "Sword-wielding Guard",
    race: "Mamool_Ja",
    link: "/wiki/Sword-wielding_Guard",
  },
  {
    name: "Tiisol Ja",
    race: "Mamool_Ja",
    link: "/wiki/Tiisol_Ja",
    gender: "Female",
  },
  {
    name: "Timid Lady",
    race: "Mamool_Ja",
    link: "/wiki/Timid_Lady",
    gender: "Female",
  },
  {
    name: "Togaal Ja",
    race: "Mamool_Ja",
    link: "/wiki/Togaal_Ja",
    gender: "Male",
  },
  {
    name: "Tojoll Ja",
    race: "Mamool_Ja",
    link: "/wiki/Tojoll_Ja",
    gender: "Male",
  },
  {
    name: "Toraal Ja",
    race: "Mamool_Ja",
    link: "/wiki/Toraal_Ja",
    gender: "Male",
  },
  {
    name: "Tuliyollal Returnee",
    race: "Mamool_Ja",
    link: "/wiki/Tuliyollal_Returnee",
    gender: "Male",
  },
  {
    name: "Unsure Citizen",
    race: "Mamool_Ja",
    link: "/wiki/Unsure_Citizen",
    gender: "Female",
  },
  {
    name: "Vedoll Ja",
    race: "Mamool_Ja",
    link: "/wiki/Vedoll_Ja",
  },
  {
    name: "Veenil Ja",
    race: "Mamool_Ja",
    link: "/wiki/Veenil_Ja",
    gender: "Female",
  },
  {
    name: "Veerul Ja",
    race: "Mamool_Ja",
    link: "/wiki/Veerul_Ja",
    gender: "Female",
  },
  {
    name: "Vugeel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Vugeel_Ja",
  },
  {
    name: "Weary Doppro",
    race: "Mamool_Ja",
    link: "/wiki/Weary_Doppro",
  },
  {
    name: "Wincing Hoobigo",
    race: "Mamool_Ja",
    link: "/wiki/Wincing_Hoobigo",
    gender: "Male",
  },
  {
    name: "Wing of Protection Scout",
    race: "Mamool_Ja",
    link: "/wiki/Wing_of_Protection_Scout",
  },
  {
    name: "Worried Wivre-handler",
    race: "Mamool_Ja",
    link: "/wiki/Worried_Wivre-handler",
  },
  {
    name: "Xeerol Ja",
    race: "Mamool_Ja",
    link: "/wiki/Xeerol_Ja",
    gender: "Female",
  },
  {
    name: "Yafaal Ja",
    race: "Mamool_Ja",
    link: "/wiki/Yafaal_Ja",
  },
  {
    name: "Young Mercenary",
    race: "Mamool_Ja",
    link: "/wiki/Young_Mercenary",
  },
  {
    name: "Zeebil Ja",
    race: "Mamool_Ja",
    link: "/wiki/Zeebil_Ja",
    gender: "Female",
  },
  {
    name: "Zereel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Zereel_Ja",
    gender: "Male",
  },
  {
    name: "Zeseel Ja",
    race: "Mamool_Ja",
    link: "/wiki/Zeseel_Ja",
    gender: "Male",
  },
  {
    name: "Ziraal Ja",
    race: "Mamool_Ja",
    link: "/wiki/Ziraal_Ja",
  },
  {
    name: "Zoraal Ja",
    race: "Mamool_Ja",
    link: "/wiki/Zoraal_Ja",
  },
  {
    name: "Ahl Ein's Kin",
    race: "Dragon",
    link: "/wiki/Ahl_Ein%27s_Kin",
  },
  {
    name: "Ahl Ein (NPC)",
    race: "Dragon",
    link: "/wiki/Ahl_Ein_(NPC)",
  },
  {
    name: "Concerned Mother",
    race: "Dragon",
    link: "/wiki/Concerned_Mother",
    gender: "Female",
  },
  {
    name: "Concerned Mother (Anyx Trine)",
    race: "Dragon",
    link: "/wiki/Concerned_Mother_(Anyx_Trine)",
    gender: "Female",
  },
  {
    name: "Ehll Tou",
    race: "Dragon",
    link: "/wiki/Ehll_Tou",
    gender: "Female",
  },
  {
    name: "Ehsk Kan",
    race: "Dragon",
    link: "/wiki/Ehsk_Kan",
  },
  {
    name: "Empty-eyed Dragon",
    race: "Dragon",
    link: "/wiki/Empty-eyed_Dragon",
    gender: "Female",
  },
  {
    name: "Ess Khas",
    race: "Dragon",
    link: "/wiki/Ess_Khas",
    gender: "Male",
  },
  {
    name: "Fjalar",
    race: "Dragon",
    link: "/wiki/Fjalar",
    gender: "Male",
  },
  {
    name: "Galar",
    race: "Dragon",
    link: "/wiki/Galar",
    gender: "Male",
  },
  {
    name: "Imperious Wyvern",
    race: "Dragon",
    link: "/wiki/Imperious_Wyvern",
  },
  {
    name: "Kohl Ahleh",
    race: "Dragon",
    link: "/wiki/Kohl_Ahleh",
  },
  {
    name: "Kohm Gahn",
    race: "Dragon",
    link: "/wiki/Kohm_Gahn",
    gender: "Male",
  },
  {
    name: "Kohm Khur",
    race: "Dragon",
    link: "/wiki/Kohm_Khur",
    gender: "Male",
  },
  {
    name: "Kohm Noskh",
    race: "Dragon",
    link: "/wiki/Kohm_Noskh",
  },
  {
    name: "Kohm Scorh",
    race: "Dragon",
    link: "/wiki/Kohm_Scorh",
    gender: "Male",
  },
  {
    name: "Midgardsormr",
    race: "Dragon",
    link: "/wiki/Midgardsormr",
    gender: "Male",
  },
  {
    name: "Ohl Ahs",
    race: "Dragon",
    link: "/wiki/Ohl_Ahs",
  },
  {
    name: "Ool Ka",
    race: "Dragon",
    link: "/wiki/Ool_Ka",
  },
  {
    name: "Pale Dragon",
    race: "Dragon",
    link: "/wiki/Pale_Dragon",
  },
  {
    name: "Rhei End",
    race: "Dragon",
    link: "/wiki/Rhei_End",
    gender: "Male",
  },
  {
    name: "Ruminating Dragon",
    race: "Dragon",
    link: "/wiki/Ruminating_Dragon",
  },
  {
    name: "Sehth Toskh",
    race: "Dragon",
    link: "/wiki/Sehth_Toskh",
  },
  {
    name: "Seih Loskh",
    race: "Dragon",
    link: "/wiki/Seih_Loskh",
  },
  {
    name: "Stoic Consort",
    race: "Dragon",
    link: "/wiki/Stoic_Consort",
    gender: "Male",
  },
  {
    name: "Unmourning Mother",
    race: "Dragon",
    link: "/wiki/Unmourning_Mother",
    gender: "Female",
  },
  {
    name: "Vedrfolnir",
    race: "Dragon",
    link: "/wiki/Vedrfolnir",
    gender: "Male",
  },
  {
    name: "Vidofnir",
    race: "Dragon",
    link: "/wiki/Vidofnir",
    gender: "Female",
  },
  {
    name: "Zenith Dragonling",
    race: "Dragon",
    link: "/wiki/Zenith_Dragonling",
  },
  {
    name: "Gaei Straightheart",
    race: "Lupin",
    link: "/wiki/Gaei_Straightheart",
    gender: "Male",
  },
  {
    name: "Hakuro",
    race: "Lupin",
    link: "/wiki/Hakuro",
  },
  {
    name: "Independent Mender (Doman Enclave)",
    race: "Lupin",
    link: "/wiki/Independent_Mender_(Doman_Enclave)",
  },
  {
    name: "Kurobana",
    race: "Lupin",
    link: "/wiki/Kurobana",
  },
  {
    name: "Masatsuchi",
    race: "Lupin",
    link: "/wiki/Masatsuchi",
  },
  {
    name: "Mauto",
    race: "Lupin",
    link: "/wiki/Mauto",
  },
  {
    name: "Soga",
    race: "Lupin",
    link: "/wiki/Soga",
  },
  {
    name: "The Wolf Burglar",
    race: "Lupin",
    link: "/wiki/The_Wolf_Burglar",
  },
  {
    name: "Ba'Gamnan",
    race: "Bangaa",
    link: "/wiki/Ba%27Gamnan",
    gender: "Male",
  },
  {
    name: "Ba'Gamnan",
    race: "Bwagi",
    link: "/wiki/Ba%27Gamnan",
    gender: "Male",
  },
  {
    name: "Ba'Gamnan",
    race: "Gijuk",
    link: "/wiki/Ba%27Gamnan",
    gender: "Male",
  },
  {
    name: "Ba'Gamnan",
    race: "Rinok",
    link: "/wiki/Ba%27Gamnan",
    gender: "Male",
  },
  {
    name: "Aggrieved Nu Mou",
    race: "Nu_Mou",
    link: "/wiki/Aggrieved_Nu_Mou",
  },
  {
    name: "Beq Lugg",
    race: "Nu_Mou",
    link: "/wiki/Beq_Lugg",
  },
  {
    name: "Caring Nu Mou",
    race: "Nu_Mou",
    link: "/wiki/Caring_Nu_Mou",
  },
  {
    name: "Daen Kenn",
    race: "Nu_Mou",
    link: "/wiki/Daen_Kenn",
  },
  {
    name: "Dozing Nu Mou",
    race: "Nu_Mou",
    link: "/wiki/Dozing_Nu_Mou",
  },
  {
    name: "Eo Sigun",
    race: "Nu_Mou",
    link: "/wiki/Eo_Sigun",
  },
  {
    name: "Gyuf Daen",
    race: "Nu_Mou",
    link: "/wiki/Gyuf_Daen",
  },
  {
    name: "Lovesick Nu Mou",
    race: "Nu_Mou",
    link: "/wiki/Lovesick_Nu_Mou",
  },
  {
    name: "Lugg Aenc",
    race: "Nu_Mou",
    link: "/wiki/Lugg_Aenc",
  },
  {
    name: "Nu Mou Culinarian",
    race: "Nu_Mou",
    link: "/wiki/Nu_Mou_Culinarian",
  },
  {
    name: "Soft-spoken Nu Mou",
    race: "Nu_Mou",
    link: "/wiki/Soft-spoken_Nu_Mou",
  },
  {
    name: "Sul Oul",
    race: "Nu_Mou",
    link: "/wiki/Sul_Oul",
  },
  {
    name: "Tyr Nee",
    race: "Nu_Mou",
    link: "/wiki/Tyr_Nee",
  },
  {
    name: "Wyd Aenc",
    race: "Nu_Mou",
    link: "/wiki/Wyd_Aenc",
  },
  {
    name: "Wyd Lad",
    race: "Nu_Mou",
    link: "/wiki/Wyd_Lad",
  },
  {
    name: "Ys Gyuf",
    race: "Nu_Mou",
    link: "/wiki/Ys_Gyuf",
  },
  {
    name: "Agitated Loporrit",
    race: "Loporrit",
    link: "/wiki/Agitated_Loporrit",
  },
  {
    name: "Aimingway",
    race: "Loporrit",
    link: "/wiki/Aimingway",
  },
  {
    name: "Ashen-furred Loporrit",
    race: "Loporrit",
    link: "/wiki/Ashen-furred_Loporrit",
  },
  {
    name: "Bashful Loporrit",
    race: "Loporrit",
    link: "/wiki/Bashful_Loporrit",
  },
  {
    name: "Blastingway",
    race: "Loporrit",
    link: "/wiki/Blastingway",
  },
  {
    name: "Boostingway",
    race: "Loporrit",
    link: "/wiki/Boostingway",
  },
  {
    name: "Bouncy Loporrit",
    race: "Loporrit",
    link: "/wiki/Bouncy_Loporrit",
  },
  {
    name: "Brawny Loporrit",
    race: "Loporrit",
    link: "/wiki/Brawny_Loporrit",
  },
  {
    name: "Brusque Loporrit",
    race: "Loporrit",
    link: "/wiki/Brusque_Loporrit",
  },
  {
    name: "Buildingway",
    race: "Loporrit",
    link: "/wiki/Buildingway",
    gender: "Male",
  },
  {
    name: "Campingway",
    race: "Loporrit",
    link: "/wiki/Campingway",
  },
  {
    name: "Cheatingway",
    race: "Loporrit",
    link: "/wiki/Cheatingway",
  },
  {
    name: "Cheerful Loporrit",
    race: "Loporrit",
    link: "/wiki/Cheerful_Loporrit",
  },
  {
    name: "Chipper Loporrit",
    race: "Loporrit",
    link: "/wiki/Chipper_Loporrit",
  },
  {
    name: "Cleanly Loporrit",
    race: "Loporrit",
    link: "/wiki/Cleanly_Loporrit",
  },
  {
    name: "Coiningway",
    race: "Loporrit",
    link: "/wiki/Coiningway",
  },
  {
    name: "Cookingway",
    race: "Loporrit",
    link: "/wiki/Cookingway",
  },
  {
    name: "Crushingway",
    race: "Loporrit",
    link: "/wiki/Crushingway",
    gender: "Female",
  },
  {
    name: "Dancingway",
    race: "Loporrit",
    link: "/wiki/Dancingway",
  },
  {
    name: "Dejected Loporrit",
    race: "Loporrit",
    link: "/wiki/Dejected_Loporrit",
  },
  {
    name: "Diggingway",
    race: "Loporrit",
    link: "/wiki/Diggingway",
  },
  {
    name: "Divingway",
    race: "Loporrit",
    link: "/wiki/Divingway",
  },
  {
    name: "Dozing Loporrit",
    race: "Loporrit",
    link: "/wiki/Dozing_Loporrit",
  },
  {
    name: "Dreamingway",
    race: "Loporrit",
    link: "/wiki/Dreamingway",
  },
  {
    name: "Drivingway",
    race: "Loporrit",
    link: "/wiki/Drivingway",
  },
  {
    name: "Drooling Loporrit",
    race: "Loporrit",
    link: "/wiki/Drooling_Loporrit",
  },
  {
    name: "Drowsy Loporrit",
    race: "Loporrit",
    link: "/wiki/Drowsy_Loporrit",
  },
  {
    name: "Easygoing Loporrit",
    race: "Loporrit",
    link: "/wiki/Easygoing_Loporrit",
  },
  {
    name: "Excitable Loporrit",
    race: "Loporrit",
    link: "/wiki/Excitable_Loporrit",
  },
  {
    name: "Fallingway",
    race: "Loporrit",
    link: "/wiki/Fallingway",
  },
  {
    name: "Famished Loporrit",
    race: "Loporrit",
    link: "/wiki/Famished_Loporrit",
  },
  {
    name: "Fidgeting Loporrit",
    race: "Loporrit",
    link: "/wiki/Fidgeting_Loporrit",
  },
  {
    name: "Fightingway",
    race: "Loporrit",
    link: "/wiki/Fightingway",
  },
  {
    name: "Fixingway",
    race: "Loporrit",
    link: "/wiki/Fixingway",
  },
  {
    name: "Floppingway",
    race: "Loporrit",
    link: "/wiki/Floppingway",
  },
  {
    name: "Flustered Loporrit",
    race: "Loporrit",
    link: "/wiki/Flustered_Loporrit",
  },
  {
    name: "Foraging Loporrit",
    race: "Loporrit",
    link: "/wiki/Foraging_Loporrit",
  },
  {
    name: "Gaining Loporrit",
    race: "Loporrit",
    link: "/wiki/Gaining_Loporrit",
  },
  {
    name: "Gamingway",
    race: "Loporrit",
    link: "/wiki/Gamingway",
  },
  {
    name: "Glaring Loporrit",
    race: "Loporrit",
    link: "/wiki/Glaring_Loporrit",
  },
  {
    name: "Goingmyway",
    race: "Loporrit",
    link: "/wiki/Goingmyway",
  },
  {
    name: "Greeningway",
    race: "Loporrit",
    link: "/wiki/Greeningway",
  },
  {
    name: "Grindingway",
    race: "Loporrit",
    link: "/wiki/Grindingway",
  },
  {
    name: "Growingway",
    race: "Loporrit",
    link: "/wiki/Growingway",
    gender: "Male",
  },
  {
    name: "Grumbling Loporrit",
    race: "Loporrit",
    link: "/wiki/Grumbling_Loporrit",
  },
  {
    name: "Guidingway",
    race: "Loporrit",
    link: "/wiki/Guidingway",
  },
  {
    name: "Hoppingway",
    race: "Loporrit",
    link: "/wiki/Hoppingway",
  },
  {
    name: "Hungry Loporrit",
    race: "Loporrit",
    link: "/wiki/Hungry_Loporrit",
  },
  {
    name: "Huntingway",
    race: "Loporrit",
    link: "/wiki/Huntingway",
  },
  {
    name: "Inquisitive Loporrit",
    race: "Loporrit",
    link: "/wiki/Inquisitive_Loporrit",
  },
  {
    name: "Inventingway",
    race: "Loporrit",
    link: "/wiki/Inventingway",
    gender: "Male",
  },
  {
    name: "Jammingway",
    race: "Loporrit",
    link: "/wiki/Jammingway",
    gender: "Male",
  },
  {
    name: "Jubilant Loporrit",
    race: "Loporrit",
    link: "/wiki/Jubilant_Loporrit",
  },
  {
    name: "Junkmonger (Bestways Burrow) (NPC)",
    race: "Loporrit",
    link: "/wiki/Junkmonger_(Bestways_Burrow)_(NPC)",
  },
  {
    name: "Keepingway",
    race: "Loporrit",
    link: "/wiki/Keepingway",
  },
  {
    name: "Knockingway",
    race: "Loporrit",
    link: "/wiki/Knockingway",
  },
  {
    name: "Knowledgeable Loporrit",
    race: "Loporrit",
    link: "/wiki/Knowledgeable_Loporrit",
  },
  {
    name: "Laboring Loporrit",
    race: "Loporrit",
    link: "/wiki/Laboring_Loporrit",
  },
  {
    name: "Laconic Loporrit",
    race: "Loporrit",
    link: "/wiki/Laconic_Loporrit",
  },
  {
    name: "Languid Loporrit",
    race: "Loporrit",
    link: "/wiki/Languid_Loporrit",
  },
  {
    name: "Learningway",
    race: "Loporrit",
    link: "/wiki/Learningway",
  },
  {
    name: "Lethargic Loporrit",
    race: "Loporrit",
    link: "/wiki/Lethargic_Loporrit",
  },
  {
    name: "Listless Loporrit",
    race: "Loporrit",
    link: "/wiki/Listless_Loporrit",
  },
  {
    name: "Livingway",
    race: "Loporrit",
    link: "/wiki/Livingway",
    gender: "Female",
  },
  {
    name: "Loporrit Junkmonger",
    race: "Loporrit",
    link: "/wiki/Loporrit_Junkmonger",
  },
  {
    name: "Loporrit Material Supplier",
    race: "Loporrit",
    link: "/wiki/Loporrit_Material_Supplier",
  },
  {
    name: "Loporrit Mechanic",
    race: "Loporrit",
    link: "/wiki/Loporrit_Mechanic",
  },
  {
    name: "Loporrit Mender",
    race: "Loporrit",
    link: "/wiki/Loporrit_Mender",
  },
  {
    name: "Loporrit Promoter",
    race: "Loporrit",
    link: "/wiki/Loporrit_Promoter",
  },
  {
    name: "Loporrit Servingway",
    race: "Loporrit",
    link: "/wiki/Loporrit_Servingway",
  },
  {
    name: "Loporrit Tailor",
    race: "Loporrit",
    link: "/wiki/Loporrit_Tailor",
  },
  {
    name: "Managingway",
    race: "Loporrit",
    link: "/wiki/Managingway",
  },
  {
    name: "Mappingway",
    race: "Loporrit",
    link: "/wiki/Mappingway",
  },
  {
    name: "Mender (Bestways Burrow)",
    race: "Loporrit",
    link: "/wiki/Mender_(Bestways_Burrow)",
  },
  {
    name: "Methodical Loporrit",
    race: "Loporrit",
    link: "/wiki/Methodical_Loporrit",
  },
  {
    name: "Mixingway",
    race: "Loporrit",
    link: "/wiki/Mixingway",
  },
  {
    name: "Mopingway",
    race: "Loporrit",
    link: "/wiki/Mopingway",
  },
  {
    name: "Muttering Loporrit",
    race: "Loporrit",
    link: "/wiki/Muttering_Loporrit",
  },
  {
    name: "Namingway (NPC)",
    race: "Loporrit",
    link: "/wiki/Namingway_(NPC)",
  },
  {
    name: "Nothingway",
    race: "Loporrit",
    link: "/wiki/Nothingway",
  },
  {
    name: "Orbitingway",
    race: "Loporrit",
    link: "/wiki/Orbitingway",
  },
  {
    name: "Overweening Loporrit",
    race: "Loporrit",
    link: "/wiki/Overweening_Loporrit",
  },
  {
    name: "Paintingway",
    race: "Loporrit",
    link: "/wiki/Paintingway",
  },
  {
    name: "Panic-stricken Loporrit",
    race: "Loporrit",
    link: "/wiki/Panic-stricken_Loporrit",
  },
  {
    name: "Peckish Loporrit",
    race: "Loporrit",
    link: "/wiki/Peckish_Loporrit",
  },
  {
    name: "Phasingway",
    race: "Loporrit",
    link: "/wiki/Phasingway",
  },
  {
    name: "Pickingway",
    race: "Loporrit",
    link: "/wiki/Pickingway",
  },
  {
    name: "Pipingway",
    race: "Loporrit",
    link: "/wiki/Pipingway",
  },
  {
    name: "Playful Loporrit",
    race: "Loporrit",
    link: "/wiki/Playful_Loporrit",
  },
  {
    name: "Preoccupied Loporrit",
    race: "Loporrit",
    link: "/wiki/Preoccupied_Loporrit",
  },
  {
    name: "Protectingway",
    race: "Loporrit",
    link: "/wiki/Protectingway",
    gender: "Female",
  },
  {
    name: "Puddingway",
    race: "Loporrit",
    link: "/wiki/Puddingway",
    gender: "Male",
  },
  {
    name: "Readingway",
    race: "Loporrit",
    link: "/wiki/Readingway",
  },
  {
    name: "Recordingway",
    race: "Loporrit",
    link: "/wiki/Recordingway",
  },
  {
    name: "Reeling Loporrit",
    race: "Loporrit",
    link: "/wiki/Reeling_Loporrit",
  },
  {
    name: "Removingway",
    race: "Loporrit",
    link: "/wiki/Removingway",
  },
  {
    name: "Repairingway",
    race: "Loporrit",
    link: "/wiki/Repairingway",
    gender: "Female",
  },
  {
    name: "Researchingway",
    race: "Loporrit",
    link: "/wiki/Researchingway",
  },
  {
    name: "Restless Loporrit",
    race: "Loporrit",
    link: "/wiki/Restless_Loporrit",
  },
  {
    name: "Ridingway",
    race: "Loporrit",
    link: "/wiki/Ridingway",
    gender: "Male",
  },
  {
    name: "Runningway?",
    race: "Loporrit",
    link: "/wiki/Runningway%3F",
  },
  {
    name: "Savingway",
    race: "Loporrit",
    link: "/wiki/Savingway",
    gender: "Male",
  },
  {
    name: "Scanningway",
    race: "Loporrit",
    link: "/wiki/Scanningway",
  },
  {
    name: "Searchingway",
    race: "Loporrit",
    link: "/wiki/Searchingway",
    gender: "Male",
  },
  {
    name: "Shakingway",
    race: "Loporrit",
    link: "/wiki/Shakingway",
    gender: "Male",
  },
  {
    name: "Shaky Loporrit",
    race: "Loporrit",
    link: "/wiki/Shaky_Loporrit",
  },
  {
    name: "Shine Supervisor",
    race: "Loporrit",
    link: "/wiki/Shine_Supervisor",
  },
  {
    name: "Singingway",
    race: "Loporrit",
    link: "/wiki/Singingway",
  },
  {
    name: "Sleepingway",
    race: "Loporrit",
    link: "/wiki/Sleepingway",
    gender: "Male",
  },
  {
    name: "Sleepy Loporrit",
    race: "Loporrit",
    link: "/wiki/Sleepy_Loporrit",
  },
  {
    name: "Smoldering Loporrit",
    race: "Loporrit",
    link: "/wiki/Smoldering_Loporrit",
  },
  {
    name: "Snappingway",
    race: "Loporrit",
    link: "/wiki/Snappingway",
  },
  {
    name: "Snappy Loporrit",
    race: "Loporrit",
    link: "/wiki/Snappy_Loporrit",
  },
  {
    name: "Sparkingway",
    race: "Loporrit",
    link: "/wiki/Sparkingway",
    gender: "Female",
  },
  {
    name: "Sparkling-eyed Loporrit",
    race: "Loporrit",
    link: "/wiki/Sparkling-eyed_Loporrit",
  },
  {
    name: "Splittingway",
    race: "Loporrit",
    link: "/wiki/Splittingway",
  },
  {
    name: "Sprightly Loporrit",
    race: "Loporrit",
    link: "/wiki/Sprightly_Loporrit",
  },
  {
    name: "Spunky Loporrit",
    race: "Loporrit",
    link: "/wiki/Spunky_Loporrit",
  },
  {
    name: "Stern Loporrit",
    race: "Loporrit",
    link: "/wiki/Stern_Loporrit",
  },
  {
    name: "Stockpiling Loporrit",
    race: "Loporrit",
    link: "/wiki/Stockpiling_Loporrit",
  },
  {
    name: "Surfingway",
    race: "Loporrit",
    link: "/wiki/Surfingway",
  },
  {
    name: "Talkingway",
    race: "Loporrit",
    link: "/wiki/Talkingway",
  },
  {
    name: "Thinkingway",
    race: "Loporrit",
    link: "/wiki/Thinkingway",
  },
  {
    name: "Thrillingway",
    race: "Loporrit",
    link: "/wiki/Thrillingway",
    gender: "Male",
  },
  {
    name: "Tradingway",
    race: "Loporrit",
    link: "/wiki/Tradingway",
  },
  {
    name: "Trembling Loporrit",
    race: "Loporrit",
    link: "/wiki/Trembling_Loporrit",
  },
  {
    name: "Unassuming Loporrit",
    race: "Loporrit",
    link: "/wiki/Unassuming_Loporrit",
  },
  {
    name: "Vacillating Loporrit",
    race: "Loporrit",
    link: "/wiki/Vacillating_Loporrit",
  },
  {
    name: "Wandering Loporrit",
    race: "Loporrit",
    link: "/wiki/Wandering_Loporrit",
  },
  {
    name: "Warringway",
    race: "Loporrit",
    link: "/wiki/Warringway",
  },
  {
    name: "Watchingway",
    race: "Loporrit",
    link: "/wiki/Watchingway",
  },
  {
    name: "Weary Loporrit",
    race: "Loporrit",
    link: "/wiki/Weary_Loporrit",
  },
  {
    name: "Weavingway",
    race: "Loporrit",
    link: "/wiki/Weavingway",
  },
  {
    name: "Wobblingway",
    race: "Loporrit",
    link: "/wiki/Wobblingway",
  },
  {
    name: "Yawningway",
    race: "Loporrit",
    link: "/wiki/Yawningway",
  },
  {
    name: "Anxious Ea",
    race: "Ea",
    link: "/wiki/Anxious_Ea",
  },
  {
    name: "Boph-bookh",
    race: "Ea",
    link: "/wiki/Boph-bookh",
  },
  {
    name: "Ceh-ceeth",
    race: "Ea",
    link: "/wiki/Ceh-ceeth",
  },
  {
    name: "Coph-coodg",
    race: "Ea",
    link: "/wiki/Coph-coodg",
  },
  {
    name: "Dew-deekh",
    race: "Ea",
    link: "/wiki/Dew-deekh",
  },
  {
    name: "Doleful Ea",
    race: "Ea",
    link: "/wiki/Doleful_Ea",
  },
  {
    name: "Eager Intellectual",
    race: "Ea",
    link: "/wiki/Eager_Intellectual",
  },
  {
    name: "Envious Ea",
    race: "Ea",
    link: "/wiki/Envious_Ea",
  },
  {
    name: "Gew-geesv",
    race: "Ea",
    link: "/wiki/Gew-geesv",
  },
  {
    name: "Ghostly Figure",
    race: "Ea",
    link: "/wiki/Ghostly_Figure",
  },
  {
    name: "Guardian Ea",
    race: "Ea",
    link: "/wiki/Guardian_Ea",
  },
  {
    name: "Inquisitive Ea",
    race: "Ea",
    link: "/wiki/Inquisitive_Ea",
  },
  {
    name: "Intrigued Ea",
    race: "Ea",
    link: "/wiki/Intrigued_Ea",
  },
  {
    name: "Jaw-jaadg",
    race: "Ea",
    link: "/wiki/Jaw-jaadg",
  },
  {
    name: "Lah-laakh",
    race: "Ea",
    link: "/wiki/Lah-laakh",
  },
  {
    name: "Laid-back Ea",
    race: "Ea",
    link: "/wiki/Laid-back_Ea",
  },
  {
    name: "Lingering Ea",
    race: "Ea",
    link: "/wiki/Lingering_Ea",
  },
  {
    name: "Meditating Ea",
    race: "Ea",
    link: "/wiki/Meditating_Ea",
  },
  {
    name: "Neh-needg",
    race: "Ea",
    link: "/wiki/Neh-needg",
  },
  {
    name: "Noh-nookh",
    race: "Ea",
    link: "/wiki/Noh-nookh",
  },
  {
    name: "Nurturing Nanny",
    race: "Ea",
    link: "/wiki/Nurturing_Nanny",
  },
  {
    name: "Row-rooth",
    race: "Ea",
    link: "/wiki/Row-rooth",
  },
  {
    name: "Sarcastic Ea",
    race: "Ea",
    link: "/wiki/Sarcastic_Ea",
  },
  {
    name: "The Anxious Ea's Friend",
    race: "Ea",
    link: "/wiki/The_Anxious_Ea%27s_Friend",
  },
  {
    name: "Thinking Ea",
    race: "Ea",
    link: "/wiki/Thinking_Ea",
  },
  {
    name: "Uninspired Intellectual",
    race: "Ea",
    link: "/wiki/Uninspired_Intellectual",
  },
  {
    name: "Weary Ea",
    race: "Ea",
    link: "/wiki/Weary_Ea",
  },
  {
    name: "Yearning Ea",
    race: "Ea",
    link: "/wiki/Yearning_Ea",
  },
  {
    name: "Defiant Fighter",
    race: "Karellian",
    link: "/wiki/Defiant_Fighter",
    gender: "Male",
  },
  {
    name: "Proud Citizen",
    race: "Karellian",
    link: "/wiki/Proud_Citizen",
    gender: "Male",
  },
  {
    name: "Emotional Grebuloff",
    race: "Grebuloff",
    link: "/wiki/Emotional_Grebuloff",
  },
  {
    name: "Nostalgic Grebuloff",
    race: "Grebuloff",
    link: "/wiki/Nostalgic_Grebuloff",
  },
  {
    name: "Overcurious Grebuloff",
    race: "Grebuloff",
    link: "/wiki/Overcurious_Grebuloff",
  },
  {
    name: "Nihilistic Nibirun",
    race: "Nibirun",
    link: "/wiki/Nihilistic_Nibirun",
    gender: "Male",
  },
  {
    name: "Drowsing Guardian",
    race: "Gordhonite",
    link: "/wiki/Drowsing_Guardian",
  },
  {
    name: "Gordhona Guardian",
    race: "Gordhonite",
    link: "/wiki/Gordhona_Guardian",
  },
  {
    name: "Snoozing Guardian",
    race: "Gordhonite",
    link: "/wiki/Snoozing_Guardian",
  },
];
